// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/customer.dart';
import 'models/detail_pembelian.dart';
import 'models/detail_stock.dart';
import 'models/invoice.dart';
import 'models/invoice/payment.dart';
import 'models/mpi.dart';
import 'models/mpi/mpiItem.dart';
import 'models/pelanggan.dart';
import 'models/pembelian.dart';
import 'models/realization.dart';
import 'models/rincian_pembayaran.dart';
import 'models/spk.dart';
import 'models/stock.dart';
import 'models/stockService/stock_realization.dart';
import 'models/supplier.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 745458929365753382),
      name: 'Customer',
      lastPropertyId: const IdUid(11, 3434357994284291078),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2322543429729524872),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4159462102279235104),
            name: 'csId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1486686031113899889),
            name: 'customerName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8750488238225982785),
            name: 'policeNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3752506444403847506),
            name: 'namaKendaraan',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8095060899457558159),
            name: 'alamat',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1119289962352442808),
            name: 'proses',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6585158967883377254),
            name: 'spkId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 5063354248052942212),
            relationTarget: 'Spk'),
        ModelProperty(
            id: const IdUid(9, 6920302302352712171),
            name: 'invId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 8135500053041788579),
            relationTarget: 'Invoice'),
        ModelProperty(
            id: const IdUid(10, 5384602353263289152),
            name: 'realizationId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 515839201963956845),
            relationTarget: 'Realization'),
        ModelProperty(
            id: const IdUid(11, 3434357994284291078),
            name: 'mpiId',
            type: 11,
            flags: 520,
            indexId: const IdUid(4, 1306563531241788222),
            relationTarget: 'Mpi')
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 3899648394111936798),
            name: 'rincian',
            targetId: const IdUid(11, 8112975015994656801))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 4267532564051428046),
      name: 'DetailPembelian',
      lastPropertyId: const IdUid(6, 5834674471862646203),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5046915864459071815),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 7896050351046937176),
            name: 'partName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1120114501388928255),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7567780596031099979),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7672913207622721487),
            name: 'price',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5834674471862646203),
            name: 'totalPrice',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 5707353236487289197),
      name: 'DetailStock',
      lastPropertyId: const IdUid(7, 6127142026764374640),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4906309131800108725),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2592130750409856914),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 9105905000071831329),
            name: 'supplier',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5366213967109445086),
            name: 'pihakId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7192670489039739974),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6976386997700370672),
            name: 'price',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6127142026764374640),
            name: 'totalPrice',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 3165534908122492960),
      name: 'Invoice',
      lastPropertyId: const IdUid(8, 5355185737646097039),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4903456972806855787),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 6680755500562664225),
            name: 'invId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4951541229410950586),
            name: 'saldo',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4294753702498882059),
            name: 'partTotal',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4162098543485240332),
            name: 'serviceTotal',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 7350841043156342700),
            name: 'invoiceTotal',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4200314686044778857),
            name: 'invoiceDate',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 5355185737646097039),
            name: 'soDate',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(2, 8876572125375253216),
            name: 'payments',
            targetId: const IdUid(7, 461355948299197699))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 7228710310078049848),
      name: 'Mpi',
      lastPropertyId: const IdUid(2, 2514280434825682869),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5303152066945420290),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2514280434825682869),
            name: 'mpiId',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(3, 6383050910052057391),
            name: 'items',
            targetId: const IdUid(6, 6508396849694241533))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 6508396849694241533),
      name: 'MpiItem',
      lastPropertyId: const IdUid(7, 4529966758026360832),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8069473499311977835),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2984491458337637721),
            name: 'category',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4420698054628947011),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3875400152751240378),
            name: 'price',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5481823111451864091),
            name: 'remark',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8389083593483358777),
            name: 'done',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4529966758026360832),
            name: 'attention',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(7, 461355948299197699),
      name: 'Payment',
      lastPropertyId: const IdUid(3, 4349027166466147647),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7181087827867877512),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 5310532903344811402),
            name: 'pay',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4349027166466147647),
            name: 'date',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(8, 4231891392643915930),
      name: 'Pelanggan',
      lastPropertyId: const IdUid(5, 228669662714724332),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4092493598295712006),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4591236730173982826),
            name: 'namaPelanggan',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 206385186470449517),
            name: 'nomorHp',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1056757794145561075),
            name: 'alamat',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 228669662714724332),
            name: 'date',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(9, 7938775090727424681),
      name: 'Penyuplai',
      lastPropertyId: const IdUid(5, 6783068128066839005),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7549082909142473358),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 8040645283840791939),
            name: 'namaPenyuplai',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3696516184682942617),
            name: 'nomorHp',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7186106893214161687),
            name: 'alamat',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6783068128066839005),
            name: 'date',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(10, 7249660919292159282),
      name: 'Realization',
      lastPropertyId: const IdUid(6, 2649796977213601200),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1239430574524959239),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2546335628027621544),
            name: 'rlId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3992034472000088951),
            name: 'selesai',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5152584816596128964),
            name: 'biyaya',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3620492139566355430),
            name: 'dateOut',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2649796977213601200),
            name: 'done',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(4, 4173805796183523593),
            name: 'mpiItems',
            targetId: const IdUid(6, 6508396849694241533)),
        ModelRelation(
            id: const IdUid(5, 2325601314425803450),
            name: 'stockItems',
            targetId: const IdUid(14, 8252230295905294995))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(11, 8112975015994656801),
      name: 'RincianPembayarran',
      lastPropertyId: const IdUid(5, 1732365915741016725),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1925734716809141454),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2943212456241773923),
            name: 'rincianPembayarranId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5888434343774102611),
            name: 'nomorHp',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2868903761315449846),
            name: 'tanggal',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1732365915741016725),
            name: 'amount',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(12, 3389311333147401659),
      name: 'Spk',
      lastPropertyId: const IdUid(22, 7821124043581012898),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2036313179231286946),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 7853031521436688451),
            name: 'jtId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3136407084783273439),
            name: 'customerName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3207199856924153408),
            name: 'policeNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 583332186576190328),
            name: 'namaKendaraan',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4804777362297338525),
            name: 'tipeKendaraan',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2822671690712378835),
            name: 'levelPekerjaan',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6228318340789893821),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 1268583191653085332),
            name: 'km',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7347171252299267808),
            name: 'noPkb',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 6804182537668267386),
            name: 'noRangka',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 6537285385965332137),
            name: 'alamat',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 5770405988449320558),
            name: 'analisa',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 5165601188029653490),
            name: 'keluhanKonsumen',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 8693151492870885576),
            name: 'jenisPekrjaan',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 5250106259996027892),
            name: 'sukuCadang',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(17, 5131654052082902415),
            name: 'catatan',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(18, 1199497322744702189),
            name: 'namaMekanik',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(19, 8127993700823814145),
            name: 'estimasiBiyaya',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(20, 8998191852607205917),
            name: 'estimasiSelesai',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(21, 7904750356019749286),
            name: 'namaInspeektor',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(22, 7821124043581012898),
            name: 'namaAdvisor',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(13, 5389668336874805663),
      name: 'Stock',
      lastPropertyId: const IdUid(7, 6823922173508952596),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8078727726342567438),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 1612755521515953140),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6147357063854235302),
            name: 'partname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4267336037774257271),
            name: 'desc',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8994379995284502924),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8830119418651827585),
            name: 'totalPrice',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6823922173508952596),
            name: 'date',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(6, 7275607165978716096),
            name: 'items',
            targetId: const IdUid(3, 5707353236487289197))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(14, 8252230295905294995),
      name: 'StockRalization',
      lastPropertyId: const IdUid(10, 7982991647627568346),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5005904759454546772),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4263678117326537519),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5390991884097494752),
            name: 'partname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4242488554711566035),
            name: 'desc',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4852305308480745740),
            name: 'realizationId',
            type: 11,
            flags: 520,
            indexId: const IdUid(5, 3007326015940417547),
            relationTarget: 'Stock'),
        ModelProperty(
            id: const IdUid(6, 3072906914271333229),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5717857448536813574),
            name: 'price',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6152191143077776767),
            name: 'servicePrice',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 2359055127732270752),
            name: 'toalPrice',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7982991647627568346),
            name: 'done',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(15, 2609290811543905393),
      name: 'Supplier',
      lastPropertyId: const IdUid(7, 492008693173469467),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6552733856157548979),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 6281117777761137762),
            name: 'supplier',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4812390050071224507),
            name: 'desc',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3249128586996604007),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 223740548000063795),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3663653490940576907),
            name: 'pihakId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 492008693173469467),
            name: 'totalPrice',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(7, 6913169932183535864),
            name: 'items',
            targetId: const IdUid(2, 4267532564051428046)),
        ModelRelation(
            id: const IdUid(8, 3810464679638851644),
            name: 'stockItems',
            targetId: const IdUid(13, 5389668336874805663)),
        ModelRelation(
            id: const IdUid(9, 1862484081618474252),
            name: 'detailStockItems',
            targetId: const IdUid(3, 5707353236487289197))
      ],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(15, 2609290811543905393),
      lastIndexId: const IdUid(5, 3007326015940417547),
      lastRelationId: const IdUid(9, 1862484081618474252),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Customer: EntityDefinition<Customer>(
        model: _entities[0],
        toOneRelations: (Customer object) =>
            [object.spk, object.inv, object.realization, object.mpi],
        toManyRelations: (Customer object) =>
            {RelInfo<Customer>.toMany(1, object.id): object.rincian},
        getId: (Customer object) => object.id,
        setId: (Customer object, int id) {
          object.id = id;
        },
        objectToFB: (Customer object, fb.Builder fbb) {
          final csIdOffset = fbb.writeString(object.csId);
          final customerNameOffset = fbb.writeString(object.customerName);
          final policeNumberOffset = fbb.writeString(object.policeNumber);
          final namaKendaraanOffset = fbb.writeString(object.namaKendaraan);
          final alamatOffset = fbb.writeString(object.alamat);
          final prosesOffset = fbb.writeString(object.proses);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, csIdOffset);
          fbb.addOffset(2, customerNameOffset);
          fbb.addOffset(3, policeNumberOffset);
          fbb.addOffset(4, namaKendaraanOffset);
          fbb.addOffset(5, alamatOffset);
          fbb.addOffset(6, prosesOffset);
          fbb.addInt64(7, object.spk.targetId);
          fbb.addInt64(8, object.inv.targetId);
          fbb.addInt64(9, object.realization.targetId);
          fbb.addInt64(10, object.mpi.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Customer(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              csId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              proses: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              customerName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              policeNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              namaKendaraan: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              alamat: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''));
          object.spk.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.spk.attach(store);
          object.inv.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.inv.attach(store);
          object.realization.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.realization.attach(store);
          object.mpi.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.mpi.attach(store);
          InternalToManyAccess.setRelInfo(object.rincian, store,
              RelInfo<Customer>.toMany(1, object.id), store.box<Customer>());
          return object;
        }),
    DetailPembelian: EntityDefinition<DetailPembelian>(
        model: _entities[1],
        toOneRelations: (DetailPembelian object) => [],
        toManyRelations: (DetailPembelian object) => {},
        getId: (DetailPembelian object) => object.id,
        setId: (DetailPembelian object, int id) {
          object.id = id;
        },
        objectToFB: (DetailPembelian object, fb.Builder fbb) {
          final partNameOffset = fbb.writeString(object.partName);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, partNameOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.count);
          fbb.addFloat64(4, object.price);
          fbb.addFloat64(5, object.totalPrice);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DetailPembelian(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              partName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              count:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              price:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0),
              totalPrice: const fb.Float64Reader()
                  .vTableGet(buffer, rootOffset, 14, 0));

          return object;
        }),
    DetailStock: EntityDefinition<DetailStock>(
        model: _entities[2],
        toOneRelations: (DetailStock object) => [],
        toManyRelations: (DetailStock object) => {},
        getId: (DetailStock object) => object.id,
        setId: (DetailStock object, int id) {
          object.id = id;
        },
        objectToFB: (DetailStock object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final supplierOffset = fbb.writeString(object.supplier);
          final pihakIdOffset = fbb.writeString(object.pihakId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dateOffset);
          fbb.addOffset(2, supplierOffset);
          fbb.addOffset(3, pihakIdOffset);
          fbb.addInt64(4, object.count);
          fbb.addFloat64(5, object.price);
          fbb.addFloat64(6, object.totalPrice);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DetailStock(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              pihakId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              supplier: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              price:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0),
              count:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              totalPrice: const fb.Float64Reader()
                  .vTableGet(buffer, rootOffset, 16, 0));

          return object;
        }),
    Invoice: EntityDefinition<Invoice>(
        model: _entities[3],
        toOneRelations: (Invoice object) => [],
        toManyRelations: (Invoice object) =>
            {RelInfo<Invoice>.toMany(2, object.id): object.payments},
        getId: (Invoice object) => object.id,
        setId: (Invoice object, int id) {
          object.id = id;
        },
        objectToFB: (Invoice object, fb.Builder fbb) {
          final invIdOffset = fbb.writeString(object.invId);
          final invoiceDateOffset = fbb.writeString(object.invoiceDate);
          final soDateOffset = fbb.writeString(object.soDate);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, invIdOffset);
          fbb.addFloat64(2, object.saldo);
          fbb.addFloat64(3, object.partTotal);
          fbb.addFloat64(4, object.serviceTotal);
          fbb.addFloat64(5, object.invoiceTotal);
          fbb.addOffset(6, invoiceDateOffset);
          fbb.addOffset(7, soDateOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Invoice(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              invId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              saldo:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0),
              partTotal:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              invoiceDate: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              serviceTotal:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0),
              invoiceTotal:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0),
              soDate: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''));
          InternalToManyAccess.setRelInfo(object.payments, store,
              RelInfo<Invoice>.toMany(2, object.id), store.box<Invoice>());
          return object;
        }),
    Mpi: EntityDefinition<Mpi>(
        model: _entities[4],
        toOneRelations: (Mpi object) => [],
        toManyRelations: (Mpi object) =>
            {RelInfo<Mpi>.toMany(3, object.id): object.items},
        getId: (Mpi object) => object.id,
        setId: (Mpi object, int id) {
          object.id = id;
        },
        objectToFB: (Mpi object, fb.Builder fbb) {
          final mpiIdOffset = fbb.writeString(object.mpiId);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, mpiIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Mpi(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              mpiId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));
          InternalToManyAccess.setRelInfo(object.items, store,
              RelInfo<Mpi>.toMany(3, object.id), store.box<Mpi>());
          return object;
        }),
    MpiItem: EntityDefinition<MpiItem>(
        model: _entities[5],
        toOneRelations: (MpiItem object) => [],
        toManyRelations: (MpiItem object) => {},
        getId: (MpiItem object) => object.id,
        setId: (MpiItem object, int id) {
          object.id = id;
        },
        objectToFB: (MpiItem object, fb.Builder fbb) {
          final categoryOffset = fbb.writeString(object.category);
          final nameOffset = fbb.writeString(object.name);
          final remarkOffset = fbb.writeString(object.remark);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addFloat64(3, object.price);
          fbb.addOffset(4, remarkOffset);
          fbb.addBool(5, object.done);
          fbb.addInt64(6, object.attention);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MpiItem(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              category: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              attention:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
              price:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              remark: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              done: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 14, false));

          return object;
        }),
    Payment: EntityDefinition<Payment>(
        model: _entities[6],
        toOneRelations: (Payment object) => [],
        toManyRelations: (Payment object) => {},
        getId: (Payment object) => object.id,
        setId: (Payment object, int id) {
          object.id = id;
        },
        objectToFB: (Payment object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.pay);
          fbb.addOffset(2, dateOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Payment(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              pay: const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''));

          return object;
        }),
    Pelanggan: EntityDefinition<Pelanggan>(
        model: _entities[7],
        toOneRelations: (Pelanggan object) => [],
        toManyRelations: (Pelanggan object) => {},
        getId: (Pelanggan object) => object.id,
        setId: (Pelanggan object, int id) {
          object.id = id;
        },
        objectToFB: (Pelanggan object, fb.Builder fbb) {
          final namaPelangganOffset = fbb.writeString(object.namaPelanggan);
          final nomorHpOffset = fbb.writeString(object.nomorHp);
          final alamatOffset = fbb.writeString(object.alamat);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, namaPelangganOffset);
          fbb.addOffset(2, nomorHpOffset);
          fbb.addOffset(3, alamatOffset);
          fbb.addInt64(4, object.date);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Pelanggan(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              namaPelanggan: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              date: const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              nomorHp: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              alamat: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));

          return object;
        }),
    Penyuplai: EntityDefinition<Penyuplai>(
        model: _entities[8],
        toOneRelations: (Penyuplai object) => [],
        toManyRelations: (Penyuplai object) => {},
        getId: (Penyuplai object) => object.id,
        setId: (Penyuplai object, int id) {
          object.id = id;
        },
        objectToFB: (Penyuplai object, fb.Builder fbb) {
          final namaPenyuplaiOffset = fbb.writeString(object.namaPenyuplai);
          final nomorHpOffset = fbb.writeString(object.nomorHp);
          final alamatOffset = fbb.writeString(object.alamat);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, namaPenyuplaiOffset);
          fbb.addOffset(2, nomorHpOffset);
          fbb.addOffset(3, alamatOffset);
          fbb.addInt64(4, object.date);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Penyuplai(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              namaPenyuplai: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              date: const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              nomorHp: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              alamat: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));

          return object;
        }),
    Realization: EntityDefinition<Realization>(
        model: _entities[9],
        toOneRelations: (Realization object) => [],
        toManyRelations: (Realization object) => {
              RelInfo<Realization>.toMany(4, object.id): object.mpiItems,
              RelInfo<Realization>.toMany(5, object.id): object.stockItems
            },
        getId: (Realization object) => object.id,
        setId: (Realization object, int id) {
          object.id = id;
        },
        objectToFB: (Realization object, fb.Builder fbb) {
          final rlIdOffset = fbb.writeString(object.rlId);
          final dateOutOffset = fbb.writeString(object.dateOut);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, rlIdOffset);
          fbb.addInt64(2, object.selesai);
          fbb.addFloat64(3, object.biyaya);
          fbb.addOffset(4, dateOutOffset);
          fbb.addBool(5, object.done);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Realization(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              rlId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              dateOut: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              selesai:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              biyaya:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              done: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 14, false));
          InternalToManyAccess.setRelInfo(
              object.mpiItems,
              store,
              RelInfo<Realization>.toMany(4, object.id),
              store.box<Realization>());
          InternalToManyAccess.setRelInfo(
              object.stockItems,
              store,
              RelInfo<Realization>.toMany(5, object.id),
              store.box<Realization>());
          return object;
        }),
    RincianPembayarran: EntityDefinition<RincianPembayarran>(
        model: _entities[10],
        toOneRelations: (RincianPembayarran object) => [],
        toManyRelations: (RincianPembayarran object) => {},
        getId: (RincianPembayarran object) => object.id,
        setId: (RincianPembayarran object, int id) {
          object.id = id;
        },
        objectToFB: (RincianPembayarran object, fb.Builder fbb) {
          final rincianPembayarranIdOffset =
              fbb.writeString(object.rincianPembayarranId);
          final nomorHpOffset = fbb.writeString(object.nomorHp);
          final tanggalOffset = fbb.writeString(object.tanggal);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, rincianPembayarranIdOffset);
          fbb.addOffset(2, nomorHpOffset);
          fbb.addOffset(3, tanggalOffset);
          fbb.addFloat64(4, object.amount);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = RincianPembayarran(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              rincianPembayarranId:
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGet(buffer, rootOffset, 6, ''),
              tanggal: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              nomorHp: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              amount: const fb.Float64Reader()
                  .vTableGet(buffer, rootOffset, 12, 0));

          return object;
        }),
    Spk: EntityDefinition<Spk>(
        model: _entities[11],
        toOneRelations: (Spk object) => [],
        toManyRelations: (Spk object) => {},
        getId: (Spk object) => object.id,
        setId: (Spk object, int id) {
          object.id = id;
        },
        objectToFB: (Spk object, fb.Builder fbb) {
          final jtIdOffset = fbb.writeString(object.jtId);
          final customerNameOffset = fbb.writeString(object.customerName);
          final policeNumberOffset = fbb.writeString(object.policeNumber);
          final namaKendaraanOffset = fbb.writeString(object.namaKendaraan);
          final tipeKendaraanOffset = fbb.writeString(object.tipeKendaraan);
          final dateOffset = fbb.writeString(object.date);
          final noPkbOffset = fbb.writeString(object.noPkb);
          final noRangkaOffset = fbb.writeString(object.noRangka);
          final alamatOffset = fbb.writeString(object.alamat);
          final analisaOffset = fbb.writeString(object.analisa);
          final keluhanKonsumenOffset = fbb.writeString(object.keluhanKonsumen);
          final jenisPekrjaanOffset = fbb.writeString(object.jenisPekrjaan);
          final sukuCadangOffset = fbb.writeString(object.sukuCadang);
          final catatanOffset = fbb.writeString(object.catatan);
          final namaMekanikOffset = fbb.writeString(object.namaMekanik);
          final estimasiSelesaiOffset = fbb.writeString(object.estimasiSelesai);
          final namaInspeektorOffset = fbb.writeString(object.namaInspeektor);
          final namaAdvisorOffset = fbb.writeString(object.namaAdvisor);
          fbb.startTable(23);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, jtIdOffset);
          fbb.addOffset(2, customerNameOffset);
          fbb.addOffset(3, policeNumberOffset);
          fbb.addOffset(4, namaKendaraanOffset);
          fbb.addOffset(5, tipeKendaraanOffset);
          fbb.addInt64(6, object.levelPekerjaan);
          fbb.addOffset(7, dateOffset);
          fbb.addInt64(8, object.km);
          fbb.addOffset(9, noPkbOffset);
          fbb.addOffset(10, noRangkaOffset);
          fbb.addOffset(11, alamatOffset);
          fbb.addOffset(12, analisaOffset);
          fbb.addOffset(13, keluhanKonsumenOffset);
          fbb.addOffset(14, jenisPekrjaanOffset);
          fbb.addOffset(15, sukuCadangOffset);
          fbb.addOffset(16, catatanOffset);
          fbb.addOffset(17, namaMekanikOffset);
          fbb.addFloat64(18, object.estimasiBiyaya);
          fbb.addOffset(19, estimasiSelesaiOffset);
          fbb.addOffset(20, namaInspeektorOffset);
          fbb.addOffset(21, namaAdvisorOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Spk(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              jtId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              customerName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              levelPekerjaan:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
              jenisPekrjaan: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 32, ''),
              noPkb: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, ''),
              noRangka: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              tipeKendaraan: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              sukuCadang: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 34, ''),
              km: const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
              policeNumber: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 10, ''),
              namaKendaraan: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 12, ''),
              date: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 18, ''),
              alamat: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 26, ''),
              analisa: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 28, ''),
              keluhanKonsumen: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 30, ''),
              catatan: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 36, ''),
              namaMekanik: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 38, ''),
              estimasiBiyaya: const fb.Float64Reader().vTableGet(buffer, rootOffset, 40, 0),
              estimasiSelesai: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 42, ''),
              namaAdvisor: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 46, ''),
              namaInspeektor: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 44, ''));

          return object;
        }),
    Stock: EntityDefinition<Stock>(
        model: _entities[12],
        toOneRelations: (Stock object) => [],
        toManyRelations: (Stock object) =>
            {RelInfo<Stock>.toMany(6, object.id): object.items},
        getId: (Stock object) => object.id,
        setId: (Stock object, int id) {
          object.id = id;
        },
        objectToFB: (Stock object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final partnameOffset = fbb.writeString(object.partname);
          final descOffset = fbb.writeString(object.desc);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, partnameOffset);
          fbb.addOffset(3, descOffset);
          fbb.addInt64(4, object.count);
          fbb.addFloat64(5, object.totalPrice);
          fbb.addInt64(6, object.date);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Stock(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              partname: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              date: const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
              desc: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              count:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              totalPrice: const fb.Float64Reader()
                  .vTableGet(buffer, rootOffset, 14, 0));
          InternalToManyAccess.setRelInfo(object.items, store,
              RelInfo<Stock>.toMany(6, object.id), store.box<Stock>());
          return object;
        }),
    StockRalization: EntityDefinition<StockRalization>(
        model: _entities[13],
        toOneRelations: (StockRalization object) => [object.realization],
        toManyRelations: (StockRalization object) => {},
        getId: (StockRalization object) => object.id,
        setId: (StockRalization object, int id) {
          object.id = id;
        },
        objectToFB: (StockRalization object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final partnameOffset = fbb.writeString(object.partname);
          final descOffset = fbb.writeString(object.desc);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, partnameOffset);
          fbb.addOffset(3, descOffset);
          fbb.addInt64(4, object.realization.targetId);
          fbb.addInt64(5, object.count);
          fbb.addFloat64(6, object.price);
          fbb.addFloat64(7, object.servicePrice);
          fbb.addFloat64(8, object.toalPrice);
          fbb.addBool(9, object.done);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = StockRalization(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              partname: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              desc: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              price:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0),
              count:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
              servicePrice:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0),
              toalPrice:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0),
              done: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 22, false));
          object.realization.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.realization.attach(store);
          return object;
        }),
    Supplier: EntityDefinition<Supplier>(
        model: _entities[14],
        toOneRelations: (Supplier object) => [],
        toManyRelations: (Supplier object) => {
              RelInfo<Supplier>.toMany(7, object.id): object.items,
              RelInfo<Supplier>.toMany(8, object.id): object.stockItems,
              RelInfo<Supplier>.toMany(9, object.id): object.detailStockItems
            },
        getId: (Supplier object) => object.id,
        setId: (Supplier object, int id) {
          object.id = id;
        },
        objectToFB: (Supplier object, fb.Builder fbb) {
          final supplierOffset = fbb.writeString(object.supplier);
          final descOffset = fbb.writeString(object.desc);
          final dateOffset = fbb.writeString(object.date);
          final pihakIdOffset = fbb.writeString(object.pihakId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, supplierOffset);
          fbb.addOffset(2, descOffset);
          fbb.addInt64(3, object.count);
          fbb.addOffset(4, dateOffset);
          fbb.addOffset(5, pihakIdOffset);
          fbb.addFloat64(6, object.totalPrice);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Supplier(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              pihakId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              supplier: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              desc: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              count:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              totalPrice: const fb.Float64Reader()
                  .vTableGet(buffer, rootOffset, 16, 0));
          InternalToManyAccess.setRelInfo(object.items, store,
              RelInfo<Supplier>.toMany(7, object.id), store.box<Supplier>());
          InternalToManyAccess.setRelInfo(object.stockItems, store,
              RelInfo<Supplier>.toMany(8, object.id), store.box<Supplier>());
          InternalToManyAccess.setRelInfo(object.detailStockItems, store,
              RelInfo<Supplier>.toMany(9, object.id), store.box<Supplier>());
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Customer] entity fields to define ObjectBox queries.
class Customer_ {
  /// see [Customer.id]
  static final id = QueryIntegerProperty<Customer>(_entities[0].properties[0]);

  /// see [Customer.csId]
  static final csId = QueryStringProperty<Customer>(_entities[0].properties[1]);

  /// see [Customer.customerName]
  static final customerName =
      QueryStringProperty<Customer>(_entities[0].properties[2]);

  /// see [Customer.policeNumber]
  static final policeNumber =
      QueryStringProperty<Customer>(_entities[0].properties[3]);

  /// see [Customer.namaKendaraan]
  static final namaKendaraan =
      QueryStringProperty<Customer>(_entities[0].properties[4]);

  /// see [Customer.alamat]
  static final alamat =
      QueryStringProperty<Customer>(_entities[0].properties[5]);

  /// see [Customer.proses]
  static final proses =
      QueryStringProperty<Customer>(_entities[0].properties[6]);

  /// see [Customer.spk]
  static final spk =
      QueryRelationToOne<Customer, Spk>(_entities[0].properties[7]);

  /// see [Customer.inv]
  static final inv =
      QueryRelationToOne<Customer, Invoice>(_entities[0].properties[8]);

  /// see [Customer.realization]
  static final realization =
      QueryRelationToOne<Customer, Realization>(_entities[0].properties[9]);

  /// see [Customer.mpi]
  static final mpi =
      QueryRelationToOne<Customer, Mpi>(_entities[0].properties[10]);

  /// see [Customer.rincian]
  static final rincian = QueryRelationToMany<Customer, RincianPembayarran>(
      _entities[0].relations[0]);
}

/// [DetailPembelian] entity fields to define ObjectBox queries.
class DetailPembelian_ {
  /// see [DetailPembelian.id]
  static final id =
      QueryIntegerProperty<DetailPembelian>(_entities[1].properties[0]);

  /// see [DetailPembelian.partName]
  static final partName =
      QueryStringProperty<DetailPembelian>(_entities[1].properties[1]);

  /// see [DetailPembelian.name]
  static final name =
      QueryStringProperty<DetailPembelian>(_entities[1].properties[2]);

  /// see [DetailPembelian.count]
  static final count =
      QueryIntegerProperty<DetailPembelian>(_entities[1].properties[3]);

  /// see [DetailPembelian.price]
  static final price =
      QueryDoubleProperty<DetailPembelian>(_entities[1].properties[4]);

  /// see [DetailPembelian.totalPrice]
  static final totalPrice =
      QueryDoubleProperty<DetailPembelian>(_entities[1].properties[5]);
}

/// [DetailStock] entity fields to define ObjectBox queries.
class DetailStock_ {
  /// see [DetailStock.id]
  static final id =
      QueryIntegerProperty<DetailStock>(_entities[2].properties[0]);

  /// see [DetailStock.date]
  static final date =
      QueryStringProperty<DetailStock>(_entities[2].properties[1]);

  /// see [DetailStock.supplier]
  static final supplier =
      QueryStringProperty<DetailStock>(_entities[2].properties[2]);

  /// see [DetailStock.pihakId]
  static final pihakId =
      QueryStringProperty<DetailStock>(_entities[2].properties[3]);

  /// see [DetailStock.count]
  static final count =
      QueryIntegerProperty<DetailStock>(_entities[2].properties[4]);

  /// see [DetailStock.price]
  static final price =
      QueryDoubleProperty<DetailStock>(_entities[2].properties[5]);

  /// see [DetailStock.totalPrice]
  static final totalPrice =
      QueryDoubleProperty<DetailStock>(_entities[2].properties[6]);
}

/// [Invoice] entity fields to define ObjectBox queries.
class Invoice_ {
  /// see [Invoice.id]
  static final id = QueryIntegerProperty<Invoice>(_entities[3].properties[0]);

  /// see [Invoice.invId]
  static final invId = QueryStringProperty<Invoice>(_entities[3].properties[1]);

  /// see [Invoice.saldo]
  static final saldo = QueryDoubleProperty<Invoice>(_entities[3].properties[2]);

  /// see [Invoice.partTotal]
  static final partTotal =
      QueryDoubleProperty<Invoice>(_entities[3].properties[3]);

  /// see [Invoice.serviceTotal]
  static final serviceTotal =
      QueryDoubleProperty<Invoice>(_entities[3].properties[4]);

  /// see [Invoice.invoiceTotal]
  static final invoiceTotal =
      QueryDoubleProperty<Invoice>(_entities[3].properties[5]);

  /// see [Invoice.invoiceDate]
  static final invoiceDate =
      QueryStringProperty<Invoice>(_entities[3].properties[6]);

  /// see [Invoice.soDate]
  static final soDate =
      QueryStringProperty<Invoice>(_entities[3].properties[7]);

  /// see [Invoice.payments]
  static final payments =
      QueryRelationToMany<Invoice, Payment>(_entities[3].relations[0]);
}

/// [Mpi] entity fields to define ObjectBox queries.
class Mpi_ {
  /// see [Mpi.id]
  static final id = QueryIntegerProperty<Mpi>(_entities[4].properties[0]);

  /// see [Mpi.mpiId]
  static final mpiId = QueryStringProperty<Mpi>(_entities[4].properties[1]);

  /// see [Mpi.items]
  static final items =
      QueryRelationToMany<Mpi, MpiItem>(_entities[4].relations[0]);
}

/// [MpiItem] entity fields to define ObjectBox queries.
class MpiItem_ {
  /// see [MpiItem.id]
  static final id = QueryIntegerProperty<MpiItem>(_entities[5].properties[0]);

  /// see [MpiItem.category]
  static final category =
      QueryStringProperty<MpiItem>(_entities[5].properties[1]);

  /// see [MpiItem.name]
  static final name = QueryStringProperty<MpiItem>(_entities[5].properties[2]);

  /// see [MpiItem.price]
  static final price = QueryDoubleProperty<MpiItem>(_entities[5].properties[3]);

  /// see [MpiItem.remark]
  static final remark =
      QueryStringProperty<MpiItem>(_entities[5].properties[4]);

  /// see [MpiItem.done]
  static final done = QueryBooleanProperty<MpiItem>(_entities[5].properties[5]);

  /// see [MpiItem.attention]
  static final attention =
      QueryIntegerProperty<MpiItem>(_entities[5].properties[6]);
}

/// [Payment] entity fields to define ObjectBox queries.
class Payment_ {
  /// see [Payment.id]
  static final id = QueryIntegerProperty<Payment>(_entities[6].properties[0]);

  /// see [Payment.pay]
  static final pay = QueryDoubleProperty<Payment>(_entities[6].properties[1]);

  /// see [Payment.date]
  static final date = QueryStringProperty<Payment>(_entities[6].properties[2]);
}

/// [Pelanggan] entity fields to define ObjectBox queries.
class Pelanggan_ {
  /// see [Pelanggan.id]
  static final id = QueryIntegerProperty<Pelanggan>(_entities[7].properties[0]);

  /// see [Pelanggan.namaPelanggan]
  static final namaPelanggan =
      QueryStringProperty<Pelanggan>(_entities[7].properties[1]);

  /// see [Pelanggan.nomorHp]
  static final nomorHp =
      QueryStringProperty<Pelanggan>(_entities[7].properties[2]);

  /// see [Pelanggan.alamat]
  static final alamat =
      QueryStringProperty<Pelanggan>(_entities[7].properties[3]);

  /// see [Pelanggan.date]
  static final date =
      QueryIntegerProperty<Pelanggan>(_entities[7].properties[4]);
}

/// [Penyuplai] entity fields to define ObjectBox queries.
class Penyuplai_ {
  /// see [Penyuplai.id]
  static final id = QueryIntegerProperty<Penyuplai>(_entities[8].properties[0]);

  /// see [Penyuplai.namaPenyuplai]
  static final namaPenyuplai =
      QueryStringProperty<Penyuplai>(_entities[8].properties[1]);

  /// see [Penyuplai.nomorHp]
  static final nomorHp =
      QueryStringProperty<Penyuplai>(_entities[8].properties[2]);

  /// see [Penyuplai.alamat]
  static final alamat =
      QueryStringProperty<Penyuplai>(_entities[8].properties[3]);

  /// see [Penyuplai.date]
  static final date =
      QueryIntegerProperty<Penyuplai>(_entities[8].properties[4]);
}

/// [Realization] entity fields to define ObjectBox queries.
class Realization_ {
  /// see [Realization.id]
  static final id =
      QueryIntegerProperty<Realization>(_entities[9].properties[0]);

  /// see [Realization.rlId]
  static final rlId =
      QueryStringProperty<Realization>(_entities[9].properties[1]);

  /// see [Realization.selesai]
  static final selesai =
      QueryIntegerProperty<Realization>(_entities[9].properties[2]);

  /// see [Realization.biyaya]
  static final biyaya =
      QueryDoubleProperty<Realization>(_entities[9].properties[3]);

  /// see [Realization.dateOut]
  static final dateOut =
      QueryStringProperty<Realization>(_entities[9].properties[4]);

  /// see [Realization.done]
  static final done =
      QueryBooleanProperty<Realization>(_entities[9].properties[5]);

  /// see [Realization.mpiItems]
  static final mpiItems =
      QueryRelationToMany<Realization, MpiItem>(_entities[9].relations[0]);

  /// see [Realization.stockItems]
  static final stockItems = QueryRelationToMany<Realization, StockRalization>(
      _entities[9].relations[1]);
}

/// [RincianPembayarran] entity fields to define ObjectBox queries.
class RincianPembayarran_ {
  /// see [RincianPembayarran.id]
  static final id =
      QueryIntegerProperty<RincianPembayarran>(_entities[10].properties[0]);

  /// see [RincianPembayarran.rincianPembayarranId]
  static final rincianPembayarranId =
      QueryStringProperty<RincianPembayarran>(_entities[10].properties[1]);

  /// see [RincianPembayarran.nomorHp]
  static final nomorHp =
      QueryStringProperty<RincianPembayarran>(_entities[10].properties[2]);

  /// see [RincianPembayarran.tanggal]
  static final tanggal =
      QueryStringProperty<RincianPembayarran>(_entities[10].properties[3]);

  /// see [RincianPembayarran.amount]
  static final amount =
      QueryDoubleProperty<RincianPembayarran>(_entities[10].properties[4]);
}

/// [Spk] entity fields to define ObjectBox queries.
class Spk_ {
  /// see [Spk.id]
  static final id = QueryIntegerProperty<Spk>(_entities[11].properties[0]);

  /// see [Spk.jtId]
  static final jtId = QueryStringProperty<Spk>(_entities[11].properties[1]);

  /// see [Spk.customerName]
  static final customerName =
      QueryStringProperty<Spk>(_entities[11].properties[2]);

  /// see [Spk.policeNumber]
  static final policeNumber =
      QueryStringProperty<Spk>(_entities[11].properties[3]);

  /// see [Spk.namaKendaraan]
  static final namaKendaraan =
      QueryStringProperty<Spk>(_entities[11].properties[4]);

  /// see [Spk.tipeKendaraan]
  static final tipeKendaraan =
      QueryStringProperty<Spk>(_entities[11].properties[5]);

  /// see [Spk.levelPekerjaan]
  static final levelPekerjaan =
      QueryIntegerProperty<Spk>(_entities[11].properties[6]);

  /// see [Spk.date]
  static final date = QueryStringProperty<Spk>(_entities[11].properties[7]);

  /// see [Spk.km]
  static final km = QueryIntegerProperty<Spk>(_entities[11].properties[8]);

  /// see [Spk.noPkb]
  static final noPkb = QueryStringProperty<Spk>(_entities[11].properties[9]);

  /// see [Spk.noRangka]
  static final noRangka =
      QueryStringProperty<Spk>(_entities[11].properties[10]);

  /// see [Spk.alamat]
  static final alamat = QueryStringProperty<Spk>(_entities[11].properties[11]);

  /// see [Spk.analisa]
  static final analisa = QueryStringProperty<Spk>(_entities[11].properties[12]);

  /// see [Spk.keluhanKonsumen]
  static final keluhanKonsumen =
      QueryStringProperty<Spk>(_entities[11].properties[13]);

  /// see [Spk.jenisPekrjaan]
  static final jenisPekrjaan =
      QueryStringProperty<Spk>(_entities[11].properties[14]);

  /// see [Spk.sukuCadang]
  static final sukuCadang =
      QueryStringProperty<Spk>(_entities[11].properties[15]);

  /// see [Spk.catatan]
  static final catatan = QueryStringProperty<Spk>(_entities[11].properties[16]);

  /// see [Spk.namaMekanik]
  static final namaMekanik =
      QueryStringProperty<Spk>(_entities[11].properties[17]);

  /// see [Spk.estimasiBiyaya]
  static final estimasiBiyaya =
      QueryDoubleProperty<Spk>(_entities[11].properties[18]);

  /// see [Spk.estimasiSelesai]
  static final estimasiSelesai =
      QueryStringProperty<Spk>(_entities[11].properties[19]);

  /// see [Spk.namaInspeektor]
  static final namaInspeektor =
      QueryStringProperty<Spk>(_entities[11].properties[20]);

  /// see [Spk.namaAdvisor]
  static final namaAdvisor =
      QueryStringProperty<Spk>(_entities[11].properties[21]);
}

/// [Stock] entity fields to define ObjectBox queries.
class Stock_ {
  /// see [Stock.id]
  static final id = QueryIntegerProperty<Stock>(_entities[12].properties[0]);

  /// see [Stock.name]
  static final name = QueryStringProperty<Stock>(_entities[12].properties[1]);

  /// see [Stock.partname]
  static final partname =
      QueryStringProperty<Stock>(_entities[12].properties[2]);

  /// see [Stock.desc]
  static final desc = QueryStringProperty<Stock>(_entities[12].properties[3]);

  /// see [Stock.count]
  static final count = QueryIntegerProperty<Stock>(_entities[12].properties[4]);

  /// see [Stock.totalPrice]
  static final totalPrice =
      QueryDoubleProperty<Stock>(_entities[12].properties[5]);

  /// see [Stock.date]
  static final date = QueryIntegerProperty<Stock>(_entities[12].properties[6]);

  /// see [Stock.items]
  static final items =
      QueryRelationToMany<Stock, DetailStock>(_entities[12].relations[0]);
}

/// [StockRalization] entity fields to define ObjectBox queries.
class StockRalization_ {
  /// see [StockRalization.id]
  static final id =
      QueryIntegerProperty<StockRalization>(_entities[13].properties[0]);

  /// see [StockRalization.name]
  static final name =
      QueryStringProperty<StockRalization>(_entities[13].properties[1]);

  /// see [StockRalization.partname]
  static final partname =
      QueryStringProperty<StockRalization>(_entities[13].properties[2]);

  /// see [StockRalization.desc]
  static final desc =
      QueryStringProperty<StockRalization>(_entities[13].properties[3]);

  /// see [StockRalization.realization]
  static final realization =
      QueryRelationToOne<StockRalization, Stock>(_entities[13].properties[4]);

  /// see [StockRalization.count]
  static final count =
      QueryIntegerProperty<StockRalization>(_entities[13].properties[5]);

  /// see [StockRalization.price]
  static final price =
      QueryDoubleProperty<StockRalization>(_entities[13].properties[6]);

  /// see [StockRalization.servicePrice]
  static final servicePrice =
      QueryDoubleProperty<StockRalization>(_entities[13].properties[7]);

  /// see [StockRalization.toalPrice]
  static final toalPrice =
      QueryDoubleProperty<StockRalization>(_entities[13].properties[8]);

  /// see [StockRalization.done]
  static final done =
      QueryBooleanProperty<StockRalization>(_entities[13].properties[9]);
}

/// [Supplier] entity fields to define ObjectBox queries.
class Supplier_ {
  /// see [Supplier.id]
  static final id = QueryIntegerProperty<Supplier>(_entities[14].properties[0]);

  /// see [Supplier.supplier]
  static final supplier =
      QueryStringProperty<Supplier>(_entities[14].properties[1]);

  /// see [Supplier.desc]
  static final desc =
      QueryStringProperty<Supplier>(_entities[14].properties[2]);

  /// see [Supplier.count]
  static final count =
      QueryIntegerProperty<Supplier>(_entities[14].properties[3]);

  /// see [Supplier.date]
  static final date =
      QueryStringProperty<Supplier>(_entities[14].properties[4]);

  /// see [Supplier.pihakId]
  static final pihakId =
      QueryStringProperty<Supplier>(_entities[14].properties[5]);

  /// see [Supplier.totalPrice]
  static final totalPrice =
      QueryDoubleProperty<Supplier>(_entities[14].properties[6]);

  /// see [Supplier.items]
  static final items = QueryRelationToMany<Supplier, DetailPembelian>(
      _entities[14].relations[0]);

  /// see [Supplier.stockItems]
  static final stockItems =
      QueryRelationToMany<Supplier, Stock>(_entities[14].relations[1]);

  /// see [Supplier.detailStockItems]
  static final detailStockItems =
      QueryRelationToMany<Supplier, DetailStock>(_entities[14].relations[2]);
}
